
name: github-actions-SQAdemo

on:
  push:
  pull_request:

jobs:
  vv-check-SQA:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Verification
        run: python scripts/verify.py

      - name: Print Demo Message
        run: echo "Hello from GitHub Actions! I am modifying this file "

      - name: Run Validation
        run: python scripts/validate.py

